version: '3.5'
services:

    mysql-mailcow:
      image: mariadb:10.3
      depends_on:
        - unbound-mailcow
      stop_grace_period: 45s
      volumes:
        - mysql-vol-1:/var/lib/mysql/
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
      environment:
        - TZ=${TZ}
        - MYSQL_ROOT_PASSWORD=${DBROOT}
        - MYSQL_DATABASE=${DBNAME}
        - MYSQL_USER=${DBUSER}
        - MYSQL_PASSWORD=${DBPASS}
        - MYSQL_INITDB_SKIP_TZINFO=1
      networks:
        net:
          aliases:
            - mysql
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop

    redis-mailcow:
      image: redis:5-alpine
      volumes:
        - redis-vol-1:/data/
      environment:
        - TZ=${TZ}
      networks:
        net:
          aliases:
            - redis
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop

    clamd-mailcow:
      image: mailcow/clamd:1.36
      environment:
        - TZ=${TZ}
        - SKIP_CLAMD=${SKIP_CLAMD:-n}
      volumes:
        - ./data/conf/clamav/:/etc/clamav/
      networks:
        net:
          aliases:
            - clamd
#      deploy:
#        placement:
#          constraints:
#            - node.hostname == docker-desktop

    rspamd-mailcow:
      image: mailcow/rspamd:1.68
      stop_grace_period: 30s
      depends_on:
        - nginx-mailcow
        - dovecot-mailcow
      environment:
        - TZ=${TZ}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
        - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
        - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      volumes:
        - ./data/hooks/rspamd:/hooks
        - ./data/conf/rspamd/custom/:/etc/rspamd/custom
        - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d
        - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d
        - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d
        - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
        - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local
        - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override
        - rspamd-vol-1:/var/lib/rspamd
        - ./data/Dockerfiles/rspamd/docker-entrypoint.sh:/docker-entrypoint.sh
      hostname: rspamd
      networks:
        net:
          aliases:
            - rspamd
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop

    php-fpm-mailcow:
      image: mailcow/phpfpm:1.67
      command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
      depends_on:
        - redis-mailcow
      volumes:
        - ./data/hooks/phpfpm:/hooks
        - ./data/web:/web:rw
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - ./data/conf/rspamd/custom/:/rspamd_custom_maps
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/conf/sogo/:/etc/sogo/
        - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
        - ./data/conf/phpfpm/sogo-sso/:/etc/sogo-sso/
        - ./data/conf/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf
        - ./data/conf/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
        - ./data/conf/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
        - ./data/conf/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini
        - ./data/conf/dovecot/global_sieve_before:/global_sieve/before
        - ./data/conf/dovecot/global_sieve_after:/global_sieve/after
        - ./data/assets/templates:/tpls
        - ./data/Dockerfiles/phpfpm/docker-entrypoint.sh:/docker-entrypoint.sh
      environment:
        - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
        - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - IMAP_PORT=${IMAP_PORT:-143}
        - IMAPS_PORT=${IMAPS_PORT:-993}
        - POP_PORT=${POP_PORT:-110}
        - POPS_PORT=${POPS_PORT:-995}
        - SIEVE_PORT=${SIEVE_PORT:-4190}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
        - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
        - SMTPS_PORT=${SMTPS_PORT:-465}
        - SMTP_PORT=${SMTP_PORT:-25}
        - API_KEY=${API_KEY:-invalid}
        - API_KEY_READ_ONLY=${API_KEY_READ_ONLY:-invalid}
        - API_ALLOW_FROM=${API_ALLOW_FROM:-invalid}
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
        - SKIP_SOLR=${SKIP_SOLR:-y}
        - SKIP_CLAMD=${SKIP_CLAMD:-n}
        - SKIP_SOGO=${SKIP_SOGO:-n}
        - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
        - MASTER=${MASTER:-y}
      networks:
        net:
          aliases:
            - phpfpm
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop

    sogo-mailcow:
      image: mailcow/sogo:1.81
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
        - LOG_LINES=${LOG_LINES:-9999}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - ACL_ANYONE=${ACL_ANYONE:-disallow}
        - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - SOGO_EXPIRE_SESSION=${SOGO_EXPIRE_SESSION:-480}
        - SKIP_SOGO=${SKIP_SOGO:-n}
        - MASTER=${MASTER:-y}
        - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
        - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      volumes:
        - ./data/conf/sogo/:/etc/sogo/
        - ./data/web/inc/init_db.inc.php:/init_db.inc.php
        - ./data/conf/sogo/custom-sogo.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/custom-sogo.js
        - mysql-socket-vol-1:/var/run/mysqld/
        - sogo-web-vol-1:/sogo_web
        - sogo-userdata-backup-vol-1:/sogo_backup
        - ./data/Dockerfiles/sogo/bootstrap-sogo.sh:/bootstrap-sogo.sh
      networks:
        net:
          aliases:
            - sogo
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop

    dovecot-mailcow:
      image: mailcow/dovecot:1.128
      depends_on:
        - mysql-mailcow
      volumes:
        - ./data/hooks/dovecot:/hooks
        - ./data/conf/dovecot:/etc/dovecot
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - ./data/conf/sogo/:/etc/sogo/
        - ./data/conf/phpfpm/sogo-sso/:/etc/phpfpm/
        - vmail-vol-1:/var/vmail
        - vmail-attachments-vol-1:/var/attachments
        - crypt-vol-1:/mail_crypt/
        - ./data/conf/rspamd/custom/:/etc/rspamd/custom
        - ./data/assets/templates:/templates
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/Dockerfiles/dovecot/docker-entrypoint.sh:/docker-entrypoint.sh
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
        - MAILDIR_GC_TIME=${MAILDIR_GC_TIME:-1440}
        - ACL_ANYONE=${ACL_ANYONE:-disallow}
        - SKIP_SOLR=${SKIP_SOLR:-y}
        - MAILDIR_SUB=${MAILDIR_SUB:-}
        - MASTER=${MASTER:-y}
        - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
        - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
      tty: true
      hostname: ${MAILCOW_HOSTNAME}
      networks:
        net:
          aliases:
            - dovecot
        traefik_public:
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik_public
          - traefik.tcp.services.imap.loadbalancer.server.port=143
          - traefik.tcp.routers.imap.entryPoints=imap
          - traefik.tcp.routers.imap.service=imap
          - traefik.tcp.routers.imap.rule=HostSNI(`*`)
          - traefik.tcp.services.imaps.loadbalancer.server.port=993
          - traefik.tcp.routers.imaps.entryPoints=imaps
          - traefik.tcp.routers.imaps.service=imaps
          - traefik.tcp.routers.imaps.rule=HostSNI(`*`)
          - traefik.tcp.services.pop.loadbalancer.server.port=110
          - traefik.tcp.routers.pop.entryPoints=pop
          - traefik.tcp.routers.pop.service=pop
          - traefik.tcp.routers.pop.rule=HostSNI(`*`)
          - traefik.tcp.services.pops.loadbalancer.server.port=995
          - traefik.tcp.routers.pops.entryPoints=pop
          - traefik.tcp.routers.pops.service=pop
          - traefik.tcp.routers.pops.rule=HostSNI(`*`)
          - traefik.tcp.services.sieve.loadbalancer.server.port=4190
          - traefik.tcp.routers.sieve.entryPoints=sieve
          - traefik.tcp.routers.sieve.service=sieve
          - traefik.tcp.routers.sieve.rule=HostSNI(`*`)

    postfix-mailcow:
      image: mailcow/postfix:1.51
      depends_on:
        - mysql-mailcow
      volumes:
        - ./data/hooks/postfix:/hooks
        - ./data/conf/postfix:/opt/postfix/conf
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - postfix-vol-1:/var/spool/postfix
        - crypt-vol-1:/var/lib/zeyple
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - ./data/Dockerfiles/postfix/postfix.sh:/opt/postfix.sh
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
        - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      hostname: ${MAILCOW_HOSTNAME}
      networks:
        net:
          aliases:
            - postfix
        traefik_public:
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik_public
          - traefik.tcp.services.smtp.loadbalancer.server.port=25
          - traefik.tcp.routers.smtp.entryPoints=smtp
          - traefik.tcp.routers.smtp.service=smtp
          - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
          - traefik.tcp.services.smtps.loadbalancer.server.port=465
          - traefik.tcp.routers.smtps.entryPoints=smtps
          - traefik.tcp.routers.smtps.service=smtps
          - traefik.tcp.routers.smtps.rule=HostSNI(`*`)
          - traefik.tcp.services.submission.loadbalancer.server.port=587
          - traefik.tcp.routers.submission.entryPoints=submission
          - traefik.tcp.routers.submission.service=submission
          - traefik.tcp.routers.submission.rule=HostSNI(`*`)

    memcached-mailcow:
      image: memcached:alpine
      environment:
        - TZ=${TZ}
      networks:
        net:
          aliases:
            - memcached
#      deploy:
#        placement:
#          constraints:
#            - node.hostname == docker-desktop

    nginx-mailcow:
      depends_on:
        - sogo-mailcow
        - php-fpm-mailcow
        - redis-mailcow
      image: nginx:mainline-alpine
      command: /bin/sh -c "envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active &&
        envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active &&
        envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active &&
        envsubst < /etc/nginx/conf.d/templates/sogo.template > /etc/nginx/conf.d/sogo.active &&
        . /etc/nginx/conf.d/templates/sogo.auth_request.template.sh > /etc/nginx/conf.d/sogo_proxy_auth.active &&
        . /etc/nginx/conf.d/templates/sites.template.sh > /etc/nginx/conf.d/sites.active &&
        . /etc/nginx/conf.d/templates/sogo_eas.template.sh > /etc/nginx/conf.d/sogo_eas.active &&
        nginx -qt &&
        until ping phpfpm -c1 > /dev/null; do sleep 1; done &&
        until ping sogo -c1 > /dev/null; do sleep 1; done &&
        until ping redis -c1 > /dev/null; do sleep 1; done &&
        until ping rspamd -c1 > /dev/null; do sleep 1; done &&
        exec nginx -g 'daemon off;'"
      environment:
        - HTTPS_PORT=${HTTPS_PORT:-443}
        - HTTP_PORT=${HTTP_PORT:-80}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - TZ=${TZ}
        - SKIP_SOGO=${SKIP_SOGO:-n}
        - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - ./data/assets/ssl/:/etc/ssl/mail/:ro
        - ./data/conf/nginx/:/etc/nginx/conf.d/:rw
        - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
        - sogo-web-vol-1:/usr/lib/GNUstep/SOGo/
      networks:
        net:
          aliases:
            - nginx
        traefik_public:
      deploy:
#        placement:
#          constraints:
#            - node.hostname == docker-desktop
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik_public
          - traefik.http.services.sogo.loadbalancer.server.port=8080
          - traefik.http.routers.sogo.entryPoints=web
          - traefik.http.routers.sogo.service=sogo
          - traefik.http.routers.sogo.rule=Host(`sogo.local`)

#    acme-mailcow:
#      depends_on:
#        - nginx-mailcow
#      image: mailcow/acme:1.73
#      dns:
#        - 8.8.8.8
#      environment:
#        - LOG_LINES=${LOG_LINES:-9999}
#        - ADDITIONAL_SAN=${ADDITIONAL_SAN}
#        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
#        - DBNAME=${DBNAME}
#        - DBUSER=${DBUSER}
#        - DBPASS=${DBPASS}
#        - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
#        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
#        - DIRECTORY_URL=${DIRECTORY_URL:-}
#        - ENABLE_SSL_SNI=${ENABLE_SSL_SNI:-n}
#        - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
#        - SKIP_HTTP_VERIFICATION=${SKIP_HTTP_VERIFICATION:-n}
#        - ONLY_MAILCOW_HOSTNAME=${ONLY_MAILCOW_HOSTNAME:-n}
#        - LE_STAGING=${LE_STAGING:-n}
#        - TZ=${TZ}
#        - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
#        - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
#        - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-n}
#        - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-n}
#      volumes:
#        - ./data/web/.well-known/acme-challenge:/var/www/acme:rw
#        - ./data/assets/ssl:/var/lib/acme/:rw
#        - ./data/assets/ssl-example:/var/lib/ssl-example/:ro
#        - mysql-socket-vol-1:/var/run/mysqld/
#      networks:
#        net:
#          aliases:
#            - acme
#      deploy:
#        placement:
#          constraints:
#            - node.hostname == docker-desktop

    watchdog-mailcow:
      image: mailcow/watchdog:1.81
      # Debug
      #command: /watchdog.sh
      volumes:
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
        - postfix-vol-1:/var/spool/postfix
        - ./data/assets/ssl:/etc/ssl/mail/:ro
      environment:
        - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
        - LOG_LINES=${LOG_LINES:-9999}
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - DBROOT=${DBROOT}
        - USE_WATCHDOG=${USE_WATCHDOG:-n}
        - WATCHDOG_NOTIFY_EMAIL=${WATCHDOG_NOTIFY_EMAIL}
        - WATCHDOG_NOTIFY_BAN=${WATCHDOG_NOTIFY_BAN:-y}
        - WATCHDOG_EXTERNAL_CHECKS=${WATCHDOG_EXTERNAL_CHECKS:-n}
        - WATCHDOG_MYSQL_REPLICATION_CHECKS=${WATCHDOG_MYSQL_REPLICATION_CHECKS:-n}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - IP_BY_DOCKER_API=${IP_BY_DOCKER_API:-0}
        - CHECK_UNBOUND=${CHECK_UNBOUND:-1}
        - SKIP_CLAMD=${SKIP_CLAMD:-n}
        - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
        - SKIP_SOGO=${SKIP_SOGO:-n}
        - HTTPS_PORT=${HTTPS_PORT:-443}
        - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
        - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
        - EXTERNAL_CHECKS_THRESHOLD=1
        - NGINX_THRESHOLD=5
        - UNBOUND_THRESHOLD=5
        - REDIS_THRESHOLD=5
        - MYSQL_THRESHOLD=5
        - MYSQL_REPLICATION_THRESHOLD=1
        - SOGO_THRESHOLD=3
        - POSTFIX_THRESHOLD=8
        - CLAMD_THRESHOLD=15
        - DOVECOT_THRESHOLD=12
        - DOVECOT_REPL_THRESHOLD=20
        - PHPFPM_THRESHOLD=5
        - RATELIMIT_THRESHOLD=1
        - FAIL2BAN_THRESHOLD=1
        - ACME_THRESHOLD=1
        - IPV6NAT_THRESHOLD=1
        - RSPAMD_THRESHOLD=5
        - OLEFY_THRESHOLD=5
        - MAILQ_THRESHOLD=20
        - MAILQ_CRIT=30
      networks:
        net:
          aliases:
            - watchdog
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop

    dockerapi-mailcow:
      image: mailcow/dockerapi:1.37
      environment:
        - DBROOT=${DBROOT}
        - TZ=${TZ}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        net:
          aliases:
            - dockerapi
      deploy:
        placement:
          constraints:
            - node.hostname == docker-desktop

#    solr-mailcow:
#      image: mailcow/solr:1.7
#      volumes:
#        - solr-vol-1:/opt/solr/server/solr/dovecot-fts/data
#      environment:
#        - TZ=${TZ}
#        - SOLR_HEAP=${SOLR_HEAP:-1024}
#        - SKIP_SOLR=${SKIP_SOLR:-y}
#      networks:
#        net:
#          aliases:
#            - solr
#      deploy:
#        placement:
#          constraints:
#            - node.hostname == docker-desktop

    olefy-mailcow:
      image: mailcow/olefy:1.3
      environment:
        - TZ=${TZ}
        - OLEFY_BINDADDRESS=0.0.0.0
        - OLEFY_BINDPORT=10055
        - OLEFY_TMPDIR=/tmp
        - OLEFY_PYTHON_PATH=/usr/bin/python3
        - OLEFY_OLEVBA_PATH=/usr/bin/olevba3
        - OLEFY_LOGLVL=20
        - OLEFY_MINLENGTH=500
        - OLEFY_DEL_TMP=1
      networks:
        net:
          aliases:
            - olefy
#      deploy:
#        placement:
#          constraints:
#            - node.hostname == docker-desktop

networks:
  net:
    driver: overlay
    attachable: true
  traefik_public:
    external: true

volumes:
  # Storage for email files
  vmail-vol-1:
    name: mailcow-vmail-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  # Storage for attachments (deduplicated)
  vmail-attachments-vol-1:
    name: mailcow-vmail-attachments-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  mysql-vol-1:
    name: mailcow-mysql-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  mysql-socket-vol-1:
    name: mailcow-mysql-socket-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  redis-vol-1:
    name: mailcow-redis-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  rspamd-vol-1:
    name: mailcow-rspamd-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  solr-vol-1:
    name: mailcow-solr-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  postfix-vol-1:
    name: mailcow-postfix-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  crypt-vol-1:
    name: mailcow-crypt-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  sogo-web-vol-1:
    name: mailcow-sogo-web-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
  sogo-userdata-backup-vol-1:
    name: mailcow-sogo-userdata-backup-vol-1
    driver: rexray/rbd
    driver_opts:
      size: 10
